// ==UserScript==
// @name         Grant Form Helper (Attestly)
// @namespace    https://attestly.org/
// @version      0.1.0
// @description  Paste-helper sidebar for grant application forms. Lists prepared answers from proposals/*-form-answers.md and copies them to the clipboard on click. Strictly clipboard-out — never fills, clicks, or mutates the form.
// @author       Attestly contributors
// @license      Apache-2.0
// @homepageURL  https://github.com/attestly/attestly/tree/main/tools/grant-form-helper
// @supportURL   https://github.com/attestly/attestly/issues
/* __MATCH_LINES__ */
// @run-at       document-idle
// @grant        none
// @noframes
// ==/UserScript==

/*
 * Grant Form Helper — Apache-2.0
 *
 * This script does NOT:
 *   - fill any form field
 *   - click any button on the page
 *   - read any form value back to a server
 *   - send any network request
 *   - mutate the page outside its own sidebar DOM
 *
 * It DOES:
 *   - parse a markdown file (embedded as base64) into per-field sections
 *   - render a sidebar listing each field with a Copy button
 *   - copy the field text to the OS clipboard when the user clicks Copy
 *   - (stretch) highlight the best-matching sidebar row when the user
 *     focuses a form textarea / input, and show a current-word-count badge
 *
 * The user pastes manually. Always.
 *
 * Regenerate this file via `node build.js` after editing any sourced
 * proposals/*-form-answers.md file.
 */

(function () {
  'use strict';

  // ---------------------------------------------------------------------------
  // Embedded funder payloads (generated by build.js)
  // ---------------------------------------------------------------------------

  const FUNDERS = [
/* __FUNDERS__ */
  ];

  // ---------------------------------------------------------------------------
  // Utilities
  // ---------------------------------------------------------------------------

  /** Decode base64 to a UTF-8 string. atob returns latin1; we go via Uint8Array
   *  so multi-byte characters in the markdown (e.g. em-dashes, accents) survive. */
  function b64ToUtf8(b64) {
    const bin = atob(b64);
    const bytes = new Uint8Array(bin.length);
    for (let i = 0; i < bin.length; i++) bytes[i] = bin.charCodeAt(i);
    return new TextDecoder('utf-8').decode(bytes);
  }

  /** Count words in a string, ignoring markdown fences and link-only lines. */
  function countWords(s) {
    if (!s) return 0;
    // Strip fenced code blocks for the count — they're usually short values
    // (URLs, titles) and we still want to count them, so include them.
    // Strip markdown emphasis markers and headings.
    const cleaned = s
      .replace(/```[\s\S]*?```/g, (block) => block.replace(/```/g, ''))
      .replace(/[*_#>`]/g, ' ');
    const m = cleaned.match(/\S+/g);
    return m ? m.length : 0;
  }

  /** Very small Levenshtein implementation — used only for short field names
   *  (≤ ~80 chars) so the O(n*m) table is fine. */
  function levenshtein(a, b) {
    a = a.toLowerCase();
    b = b.toLowerCase();
    if (a === b) return 0;
    if (!a.length) return b.length;
    if (!b.length) return a.length;
    const prev = new Array(b.length + 1);
    const curr = new Array(b.length + 1);
    for (let j = 0; j <= b.length; j++) prev[j] = j;
    for (let i = 1; i <= a.length; i++) {
      curr[0] = i;
      for (let j = 1; j <= b.length; j++) {
        const cost = a.charCodeAt(i - 1) === b.charCodeAt(j - 1) ? 0 : 1;
        curr[j] = Math.min(curr[j - 1] + 1, prev[j] + 1, prev[j - 1] + cost);
      }
      for (let j = 0; j <= b.length; j++) prev[j] = curr[j];
    }
    return prev[b.length];
  }

  /** Similarity in [0,1]; 1 means identical. Combines substring containment
   *  (weighted heavily) with normalised Levenshtein. */
  function similarity(needle, hay) {
    if (!needle || !hay) return 0;
    const a = needle.toLowerCase().trim();
    const b = hay.toLowerCase().trim();
    if (!a || !b) return 0;
    if (a === b) return 1;
    if (b.includes(a) || a.includes(b)) {
      return 0.85 + 0.15 * (Math.min(a.length, b.length) / Math.max(a.length, b.length));
    }
    const dist = levenshtein(a, b);
    const maxLen = Math.max(a.length, b.length);
    return 1 - dist / maxLen;
  }

  // ---------------------------------------------------------------------------
  // Markdown parsing — H2-anchored per-field sections
  // ---------------------------------------------------------------------------

  /**
   * Parse a markdown blob into [{ heading, body, wordCount }, ...]:
   *   - Each H2 ("## ...") opens a new section.
   *   - H1 ("# ...") lines are treated as scope markers (e.g. "TAB 1 — ...")
   *     and are NOT separate fields. The most recent H1 is attached to each
   *     following section as `.scope` so the sidebar can show "TAB 1 / Field".
   *   - H3+ lines stay inside their parent H2 body.
   *   - Leading/trailing whitespace in each body is trimmed.
   */
  function parseSections(md) {
    const lines = md.split(/\r?\n/);
    const sections = [];
    let scope = null;
    let current = null;

    for (const line of lines) {
      const h1 = /^#\s+(.+?)\s*$/.exec(line);
      const h2 = /^##\s+(.+?)\s*$/.exec(line);
      if (h1 && !h2) {
        scope = h1[1].trim();
        continue;
      }
      if (h2) {
        if (current) sections.push(current);
        current = {
          heading: h2[1].trim(),
          scope,
          bodyLines: [],
        };
        continue;
      }
      if (current) {
        current.bodyLines.push(line);
      }
    }
    if (current) sections.push(current);

    return sections.map((s, idx) => {
      const body = s.bodyLines.join('\n').replace(/^\s+|\s+$/g, '');
      return {
        index: idx,
        heading: s.heading,
        scope: s.scope,
        body,
        wordCount: countWords(body),
      };
    });
  }

  /** Strip markdown wrappers so the clipboard payload is closer to "what you
   *  want to paste into the textarea". Specifically:
   *    - Single fenced code blocks ("```...```") that fill the body become
   *      their inner content (handles the URL/title-style fields).
   *    - Leading/trailing whitespace is trimmed.
   *    - Word-count footer lines ("**~165 words.**") are stripped — they're
   *      meta, not field content.
   */
  function clipboardPayload(body) {
    if (!body) return '';
    let out = body;
    // Strip trailing word-count notes like "**~175 words.**" or "**~95 words.**"
    out = out.replace(/\n+\s*\*\*~\d+\s+words?\.?\*\*\s*$/i, '');
    // If the whole body is a single fenced code block, unwrap it.
    const wholeFence = /^\s*```[^\n]*\n([\s\S]*?)\n?```\s*$/m.exec(out.trim());
    if (wholeFence && wholeFence[0].trim() === out.trim()) {
      out = wholeFence[1];
    }
    return out.replace(/^\s+|\s+$/g, '');
  }

  // ---------------------------------------------------------------------------
  // Clipboard
  // ---------------------------------------------------------------------------

  async function copyToClipboard(text) {
    // Prefer the modern API; fall back to a textarea + execCommand for
    // browsers / contexts where it's unavailable. Both paths copy text only.
    if (navigator.clipboard && window.isSecureContext) {
      try {
        await navigator.clipboard.writeText(text);
        return true;
      } catch (err) {
        // fall through to legacy path
        console.warn('[grant-form-helper] clipboard.writeText failed, using fallback', err);
      }
    }
    const ta = document.createElement('textarea');
    ta.value = text;
    ta.setAttribute('readonly', '');
    ta.style.position = 'fixed';
    ta.style.top = '-1000px';
    ta.style.opacity = '0';
    document.body.appendChild(ta);
    ta.select();
    let ok = false;
    try {
      ok = document.execCommand('copy');
    } catch (err) {
      ok = false;
    }
    document.body.removeChild(ta);
    return ok;
  }

  // ---------------------------------------------------------------------------
  // Sidebar UI
  // ---------------------------------------------------------------------------

  const STYLE = `
.gfh-root, .gfh-root * {
  box-sizing: border-box;
  font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, sans-serif;
  font-size: 13px;
  line-height: 1.4;
  color: #1f2328;
}
.gfh-root {
  position: fixed;
  top: 64px;
  right: 16px;
  width: 360px;
  max-height: calc(100vh - 96px);
  background: #ffffff;
  border: 1px solid #d0d7de;
  border-radius: 10px;
  box-shadow: 0 8px 24px rgba(31, 35, 40, 0.12);
  z-index: 2147483646;
  display: flex;
  flex-direction: column;
  overflow: hidden;
  user-select: none;
}
.gfh-root.gfh-collapsed { width: auto; }
.gfh-root.gfh-collapsed .gfh-body,
.gfh-root.gfh-collapsed .gfh-funder,
.gfh-root.gfh-collapsed .gfh-search { display: none; }
.gfh-header {
  display: flex;
  align-items: center;
  gap: 8px;
  padding: 8px 10px;
  background: #f6f8fa;
  border-bottom: 1px solid #d0d7de;
  cursor: grab;
}
.gfh-header.gfh-dragging { cursor: grabbing; }
.gfh-title {
  flex: 1 1 auto;
  font-weight: 600;
  font-size: 13px;
  white-space: nowrap;
  overflow: hidden;
  text-overflow: ellipsis;
}
.gfh-btn {
  appearance: none;
  border: 1px solid #d0d7de;
  background: #ffffff;
  border-radius: 6px;
  padding: 3px 8px;
  font-size: 12px;
  cursor: pointer;
  user-select: none;
  color: #1f2328;
}
.gfh-btn:hover { background: #f3f4f6; }
.gfh-btn:active { background: #e5e7eb; }
.gfh-btn-toggle {
  width: 28px;
  text-align: center;
  padding: 3px 0;
}
.gfh-funder, .gfh-search {
  padding: 6px 10px;
  border-bottom: 1px solid #eaeef2;
  background: #fcfcfd;
}
.gfh-funder select, .gfh-search input {
  width: 100%;
  border: 1px solid #d0d7de;
  border-radius: 6px;
  padding: 4px 6px;
  font-size: 12px;
  background: #ffffff;
  color: #1f2328;
  user-select: text;
}
.gfh-body {
  overflow-y: auto;
  flex: 1 1 auto;
  padding: 4px 0;
}
.gfh-scope {
  padding: 6px 10px 2px;
  font-size: 11px;
  text-transform: uppercase;
  letter-spacing: 0.04em;
  font-weight: 600;
  color: #57606a;
  background: #fcfcfd;
  border-top: 1px solid #eaeef2;
}
.gfh-scope:first-child { border-top: none; }
.gfh-row {
  display: flex;
  align-items: center;
  gap: 8px;
  padding: 6px 10px;
  border-top: 1px solid #f3f4f6;
}
.gfh-row:first-child { border-top: none; }
.gfh-row:hover { background: #f6f8fa; }
.gfh-row.gfh-highlight {
  background: #fff8c5;
  border-left: 3px solid #d4a72c;
  padding-left: 7px;
}
.gfh-row-info {
  flex: 1 1 auto;
  min-width: 0;
}
.gfh-row-heading {
  font-size: 12px;
  font-weight: 500;
  white-space: nowrap;
  overflow: hidden;
  text-overflow: ellipsis;
  user-select: text;
}
.gfh-row-meta {
  font-size: 11px;
  color: #57606a;
  margin-top: 2px;
  display: flex;
  gap: 6px;
  align-items: center;
}
.gfh-badge {
  display: inline-block;
  padding: 1px 6px;
  border-radius: 10px;
  font-size: 10px;
  background: #ddf4ff;
  color: #0969da;
}
.gfh-badge-over { background: #ffebe9; color: #cf222e; }
.gfh-badge-under { background: #dafbe1; color: #1a7f37; }
.gfh-copy {
  flex: 0 0 auto;
}
.gfh-copy.gfh-copied { background: #1a7f37; color: #ffffff; border-color: #1a7f37; }
.gfh-toast {
  position: fixed;
  bottom: 24px;
  right: 24px;
  background: #1f2328;
  color: #ffffff;
  padding: 8px 14px;
  border-radius: 6px;
  font-size: 13px;
  font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif;
  z-index: 2147483647;
  opacity: 0;
  transition: opacity 0.18s ease;
  pointer-events: none;
}
.gfh-toast.gfh-show { opacity: 1; }
.gfh-launcher {
  position: fixed;
  top: 64px;
  right: 16px;
  z-index: 2147483646;
  background: #1f2328;
  color: #ffffff;
  border: none;
  border-radius: 20px;
  padding: 6px 12px;
  font-size: 12px;
  font-weight: 600;
  cursor: pointer;
  box-shadow: 0 4px 12px rgba(31, 35, 40, 0.2);
  font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif;
}
.gfh-launcher:hover { background: #2c333a; }
`;

  let toastTimer = null;
  function showToast(msg) {
    let toast = document.querySelector('.gfh-toast');
    if (!toast) {
      toast = document.createElement('div');
      toast.className = 'gfh-toast';
      document.body.appendChild(toast);
    }
    toast.textContent = msg;
    toast.classList.add('gfh-show');
    if (toastTimer) clearTimeout(toastTimer);
    toastTimer = setTimeout(() => toast.classList.remove('gfh-show'), 1500);
  }

  // Best-effort label extraction for a focused form field — used by the
  // stretch fuzzy-match feature. Read-only; never mutates the page.
  function describeField(el) {
    if (!el) return '';
    const parts = [];
    if (el.id) {
      const lbl = document.querySelector(`label[for="${CSS.escape(el.id)}"]`);
      if (lbl && lbl.textContent) parts.push(lbl.textContent);
    }
    if (el.getAttribute) {
      for (const a of ['aria-label', 'placeholder', 'name', 'data-field', 'data-name']) {
        const v = el.getAttribute(a);
        if (v) parts.push(v);
      }
    }
    // Walk up a few ancestors looking for a wrapping label.
    let node = el.parentElement;
    let hops = 0;
    while (node && hops < 4) {
      if (node.tagName === 'LABEL') {
        if (node.textContent) parts.push(node.textContent);
        break;
      }
      node = node.parentElement;
      hops++;
    }
    return parts.join(' ').replace(/\s+/g, ' ').trim();
  }

  function buildSidebar(sections, funders, activeFunderId, onSwitchFunder) {
    const root = document.createElement('div');
    root.className = 'gfh-root';
    root.setAttribute('role', 'complementary');
    root.setAttribute('aria-label', 'Grant form paste helper');

    // Header
    const header = document.createElement('div');
    header.className = 'gfh-header';
    const title = document.createElement('div');
    title.className = 'gfh-title';
    title.textContent = 'Grant Form Helper';
    const toggle = document.createElement('button');
    toggle.className = 'gfh-btn gfh-btn-toggle';
    toggle.title = 'Collapse / expand';
    toggle.setAttribute('aria-label', 'Collapse sidebar');
    toggle.textContent = '–';
    toggle.addEventListener('click', () => {
      const collapsed = root.classList.toggle('gfh-collapsed');
      toggle.textContent = collapsed ? '+' : '–';
      toggle.setAttribute('aria-label', collapsed ? 'Expand sidebar' : 'Collapse sidebar');
    });
    header.appendChild(title);
    header.appendChild(toggle);
    root.appendChild(header);

    // Funder switcher (only shown when > 1 funder is embedded)
    if (funders.length > 1) {
      const funderWrap = document.createElement('div');
      funderWrap.className = 'gfh-funder';
      const sel = document.createElement('select');
      sel.setAttribute('aria-label', 'Switch funder');
      for (const f of funders) {
        const opt = document.createElement('option');
        opt.value = f.id;
        opt.textContent = f.label;
        if (f.id === activeFunderId) opt.selected = true;
        sel.appendChild(opt);
      }
      sel.addEventListener('change', () => onSwitchFunder(sel.value));
      funderWrap.appendChild(sel);
      root.appendChild(funderWrap);
    }

    // Search filter
    const searchWrap = document.createElement('div');
    searchWrap.className = 'gfh-search';
    const search = document.createElement('input');
    search.type = 'search';
    search.placeholder = 'Filter fields…';
    search.setAttribute('aria-label', 'Filter fields by name');
    searchWrap.appendChild(search);
    root.appendChild(searchWrap);

    // Body
    const body = document.createElement('div');
    body.className = 'gfh-body';
    root.appendChild(body);

    const rowEls = []; // [{ section, el, headingLower }]
    let lastScope = null;
    for (const s of sections) {
      if (s.scope && s.scope !== lastScope) {
        const scopeEl = document.createElement('div');
        scopeEl.className = 'gfh-scope';
        scopeEl.textContent = s.scope;
        body.appendChild(scopeEl);
        lastScope = s.scope;
      }

      const row = document.createElement('div');
      row.className = 'gfh-row';
      row.dataset.index = String(s.index);

      const info = document.createElement('div');
      info.className = 'gfh-row-info';
      const h = document.createElement('div');
      h.className = 'gfh-row-heading';
      h.textContent = s.heading;
      h.title = s.heading;
      info.appendChild(h);
      const meta = document.createElement('div');
      meta.className = 'gfh-row-meta';
      const badge = document.createElement('span');
      badge.className = 'gfh-badge';
      badge.textContent = `${s.wordCount} words`;
      meta.appendChild(badge);
      info.appendChild(meta);
      row.appendChild(info);

      const copyBtn = document.createElement('button');
      copyBtn.className = 'gfh-btn gfh-copy';
      copyBtn.type = 'button';
      copyBtn.textContent = 'Copy';
      copyBtn.setAttribute('aria-label', `Copy answer for ${s.heading}`);
      copyBtn.addEventListener('click', async (ev) => {
        ev.stopPropagation();
        const payload = clipboardPayload(s.body);
        const ok = await copyToClipboard(payload);
        if (ok) {
          copyBtn.classList.add('gfh-copied');
          copyBtn.textContent = 'Copied';
          showToast(`Copied: ${s.heading}`);
          setTimeout(() => {
            copyBtn.classList.remove('gfh-copied');
            copyBtn.textContent = 'Copy';
          }, 1200);
        } else {
          showToast('Copy failed — see console');
        }
      });
      row.appendChild(copyBtn);

      body.appendChild(row);
      rowEls.push({ section: s, el: row, headingLower: s.heading.toLowerCase(), badge });
    }

    // Search filter behaviour
    search.addEventListener('input', () => {
      const q = search.value.trim().toLowerCase();
      for (const r of rowEls) {
        const match = !q || r.headingLower.includes(q) || (r.section.scope && r.section.scope.toLowerCase().includes(q));
        r.el.style.display = match ? '' : 'none';
      }
    });

    // Dragging
    let drag = null;
    header.addEventListener('mousedown', (ev) => {
      if (ev.target === toggle) return;
      drag = {
        startX: ev.clientX,
        startY: ev.clientY,
        rect: root.getBoundingClientRect(),
      };
      header.classList.add('gfh-dragging');
      ev.preventDefault();
    });
    window.addEventListener('mousemove', (ev) => {
      if (!drag) return;
      const dx = ev.clientX - drag.startX;
      const dy = ev.clientY - drag.startY;
      const left = Math.max(4, Math.min(window.innerWidth - 60, drag.rect.left + dx));
      const top = Math.max(4, Math.min(window.innerHeight - 60, drag.rect.top + dy));
      root.style.left = left + 'px';
      root.style.top = top + 'px';
      root.style.right = 'auto';
    });
    window.addEventListener('mouseup', () => {
      if (drag) {
        drag = null;
        header.classList.remove('gfh-dragging');
      }
    });

    // Stretch: focus-driven fuzzy match + live word-count badge on active field
    let activeFocus = null;
    function clearHighlight() {
      for (const r of rowEls) r.el.classList.remove('gfh-highlight');
    }
    function updateWordBadge() {
      if (!activeFocus) return;
      const live = activeFocus.value != null
        ? activeFocus.value
        : (activeFocus.textContent || '');
      const w = countWords(live);
      // Find which row is currently highlighted, if any, and annotate its badge.
      const r = rowEls.find((x) => x.el.classList.contains('gfh-highlight'));
      if (!r) return;
      const target = r.section.wordCount;
      r.badge.textContent = `${w} / ~${target}`;
      r.badge.classList.toggle('gfh-badge-over', target > 0 && w > target * 1.1);
      r.badge.classList.toggle('gfh-badge-under', target > 0 && w < target * 0.6);
    }
    function resetWordBadge(r) {
      r.badge.textContent = `${r.section.wordCount} words`;
      r.badge.classList.remove('gfh-badge-over');
      r.badge.classList.remove('gfh-badge-under');
    }
    function onFocusIn(ev) {
      const el = ev.target;
      if (!el || root.contains(el)) return;
      const tag = (el.tagName || '').toLowerCase();
      if (tag !== 'textarea' && tag !== 'input' && el.contentEditable !== 'true') return;
      activeFocus = el;
      const label = describeField(el);
      if (!label) return;
      // Rank rows by similarity to the label; only highlight if confidence is real.
      let best = null;
      let bestScore = 0.4;
      for (const r of rowEls) {
        const score = similarity(r.headingLower, label);
        if (score > bestScore) { best = r; bestScore = score; }
      }
      // Reset every row's badge first
      for (const r of rowEls) resetWordBadge(r);
      clearHighlight();
      if (best) {
        best.el.classList.add('gfh-highlight');
        best.el.scrollIntoView({ block: 'nearest', behavior: 'smooth' });
        updateWordBadge();
      }
    }
    function onInput(ev) {
      if (ev.target === activeFocus) updateWordBadge();
    }
    function onFocusOut() {
      // Keep the highlight a bit so the user can still read it during paste.
    }
    document.addEventListener('focusin', onFocusIn, true);
    document.addEventListener('input', onInput, true);
    document.addEventListener('focusout', onFocusOut, true);

    // Expose a teardown so mount() can detach these document-level listeners
    // when re-mounting (funder switch). Without this we'd leak one handler set
    // per switch — harmless functionally but untidy.
    root._gfhTeardown = function teardown() {
      document.removeEventListener('focusin', onFocusIn, true);
      document.removeEventListener('input', onInput, true);
      document.removeEventListener('focusout', onFocusOut, true);
    };

    return root;
  }

  // ---------------------------------------------------------------------------
  // Mount
  // ---------------------------------------------------------------------------

  function pickFunderForLocation() {
    const href = location.href;
    for (const f of FUNDERS) {
      for (const pat of f.matches) {
        // Convert a Tampermonkey @match-style pattern (with one '*' for path)
        // into a simple prefix check. Good enough for our portal whitelist.
        const prefix = pat.replace(/\*+$/, '');
        if (href.startsWith(prefix)) return f.id;
      }
    }
    return FUNDERS[0] && FUNDERS[0].id;
  }

  function injectStyleOnce() {
    if (document.getElementById('gfh-style')) return;
    const style = document.createElement('style');
    style.id = 'gfh-style';
    style.textContent = STYLE;
    document.documentElement.appendChild(style);
  }

  let currentRoot = null;
  function mount(funderId) {
    const funder = FUNDERS.find((f) => f.id === funderId) || FUNDERS[0];
    if (!funder) {
      console.warn('[grant-form-helper] no funders embedded');
      return;
    }
    let md;
    try {
      md = b64ToUtf8(funder.b64);
    } catch (err) {
      console.error('[grant-form-helper] base64 decode failed', err);
      return;
    }
    const sections = parseSections(md);
    if (currentRoot) {
      if (typeof currentRoot._gfhTeardown === 'function') currentRoot._gfhTeardown();
      if (currentRoot.parentNode) currentRoot.parentNode.removeChild(currentRoot);
    }
    currentRoot = buildSidebar(sections, FUNDERS, funder.id, (newId) => mount(newId));
    document.body.appendChild(currentRoot);
  }

  function init() {
    injectStyleOnce();
    mount(pickFunderForLocation());
  }

  if (document.readyState === 'loading') {
    document.addEventListener('DOMContentLoaded', init, { once: true });
  } else {
    init();
  }
})();
